# SPDX-License-Identifier: GPL-3.0-or-later
# A user manager cannot order after the system's network-online.target, so the
# unit's After= does nothing: at boot netmuxd started before the route existed,
# failed the phone's heartbeat ("Network is unreachable") and never retried.
[Service]
ExecStartPre=/bin/sh -c 'until ip -4 route show default | grep -q .; do sleep 1; done'
TimeoutStartSec=120
