#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the prefix registry seed from the staged builtin DLLs.

A Wine prefix normally gets its COM classes (and the rest of each builtin's
registration) from `wineboot`, which runs setupapi's register_fake_dll over
every builtin: each DLL carries its registration as WINE_REGISTRY resources
(ATL registrar scripts generated by widl), applied with the replacements
%MODULE% = C:\\windows\\system32\\<dll> and %SystemRoot% = C:\\windows.
The app never runs wineboot (one process, no services), so its prefix had no
Classes\\CLSID keys at all and CoCreateInstance(CLSID_MMDeviceEnumerator)
failed with REGDB_E_CLASSNOTREG on the device.

This script does the same registration at build time: it reads every
WINE_REGISTRY script in the staged arm64ec-windows set (the DLLs x86-64
guests load), interprets it with the rules of Wine's registrar
(dlls/atl/registrar.c do_process_key), and writes the resulting keys in
wineserver's registry file format:

  app/registry/system.reg   HKLM and HKCR keys (relative to \\Machine)
  app/registry/user.reg     HKCU keys (relative to the user key)

Both also carry the user profile keys wineboot and shell32 would otherwise
write (PROFILE below): the ProfileList, the user shell folders and the
Volatile Environment that gives a guest %USERPROFILE%, %APPDATA% and
%LOCALAPPDATA%. wine_host.c creates the directories they name.

wine_host.c appends every section a prefix's system.reg / user.reg does not
have yet, before the wineserver loads them, on every launch. So a fresh
install, an existing prefix and an app update that ships more DLLs all end up
registered, and nothing the prefix already holds is overwritten. A PROFILE
section is preceded by the MARKER comment line: for a marked key the prefix
already has, the values it lacks are added too (ntdll and shell32 create those
keys empty); any other key the prefix has is left alone.

Usage:
  prefix-registry.py            regenerate from app/Sources/S1Probe/Runtime/arm64ec-windows
  prefix-registry.py --check    fail if the committed files differ from a regeneration
Run it after build/stages/stage-artifacts.py stage (the staged DLLs are hash-checked there).
"""

import argparse
import os
import sys
import uuid
from pathlib import Path

import pefile

PKG = Path(__file__).resolve().parent.parent
RUNTIME = PKG / "Sources" / "S1Probe" / "Runtime" / "arm64ec-windows"
OUT = PKG / "registry"
SYSTEM32 = "C:\\windows\\system32"
SYSTEMROOT = "C:\\windows"
ROOTS = {  # registrar root key -> (hive, prefix inside the hive file)
    "HKCR": ("system", "Software\\Classes"),
    "HKEY_CLASSES_ROOT": ("system", "Software\\Classes"),
    "HKLM": ("system", ""),
    "HKEY_LOCAL_MACHINE": ("system", ""),
    "HKCU": ("user", ""),
    "HKEY_CURRENT_USER": ("user", ""),
}
# The guest's user name: wine_host.c sets USER to it (WINE_HOST_USER), and ntdll
# reports it as the Windows user, so C:\\users\\<USER> is the profile shell32
# resolves %USERPROFILE% to. The two must agree.
USER = "playport"
PROFILE_DIR = f"C:\\users\\{USER}"
# The keys a wineboot'ed prefix has for its user profile: the ProfileList values
# shell32 writes on first use (dlls/shell32/shellpath.c _SHGetProfilesValue),
# the AppData user shell folders (value names as shellpath.c CSIDL_Data gives
# them; LocalLow has only its FOLDERID), and wineboot's
# create_volatile_environment_registry_key, which ntdll reads into the
# environment of every process (dlls/ntdll/unix/env.c add_registry_environment),
# as it reads the system environment wine.inf writes (loader/wine.inf.in,
# Session Manager\Environment). Without that key a guest has no PATH at all:
# Kingdom Come's launcher adds Bin\Win64Shared to PATH before it loads its DLLs
# from there, and when GetEnvironmentVariableW("PATH") fails it loads none and
# exits (docs/evidence/2026-10-01-kcd-system-environment.md).
PROFILE = {
    "system": {
        "System\\CurrentControlSet\\Control\\Session Manager\\Environment": [
            ("ComSpec", "expand_sz", "%SystemRoot%\\system32\\cmd.exe"),
            ("OS", "sz", "Windows_NT"),
            ("PATH", "expand_sz", "%SystemRoot%\\system32;%SystemRoot%;%SystemRoot%\\system32\\wbem;"
                                  "%SystemRoot%\\system32\\WindowsPowershell\\v1.0"),
            ("PATHEXT", "sz", ".com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh"),
            ("TEMP", "expand_sz", "%SystemRoot%\\temp"),
            ("TMP", "expand_sz", "%SystemRoot%\\temp"),
            ("windir", "expand_sz", "%SystemRoot%"),
            ("winsysdir", "sz", SYSTEM32),
        ],
        "Software\\Microsoft\\Windows NT\\CurrentVersion\\ProfileList": [
            ("ProfilesDirectory", "expand_sz", "C:\\users"),
            ("ProgramData", "expand_sz", "C:\\ProgramData"),
            ("Public", "expand_sz", "C:\\users\\Public"),
        ],
    },
    "user": {
        "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders": [
            ("AppData", "expand_sz", "%USERPROFILE%\\AppData\\Roaming"),
            ("Local AppData", "expand_sz", "%USERPROFILE%\\AppData\\Local"),
            ("{A520A1A4-1780-4FF6-BD18-167343C5AF16}", "expand_sz", "%USERPROFILE%\\AppData\\LocalLow"),
        ],
        "Volatile Environment": [
            ("APPDATA", "sz", PROFILE_DIR + "\\AppData\\Roaming"),
            ("HOMEDRIVE", "sz", "C:"),
            ("HOMEPATH", "sz", PROFILE_DIR[2:]),
            ("LOCALAPPDATA", "sz", PROFILE_DIR + "\\AppData\\Local"),
            ("USERNAME", "sz", USER),
            ("USERPROFILE", "sz", PROFILE_DIR),
        ],
    },
}
# The schemes a game may open a web page with, and their handler: Playport's
# URL opener (app/UrlOpener, staged in system32), which hands the URL to the
# host app's web sheet (decision 0064). Wine's wine.inf would name
# winebrowser.exe, which the app does not ship and which cannot open anything
# on iOS. shell32 reads <scheme>\\shell\\open\\command for a URL
# (dlls/shell32/shlexec.c SHELL_execute_url). Marked like PROFILE, so a key the
# prefix already has gets the value only when it lacks one.
URL_OPENER = f'"{SYSTEM32}\\playport-url-opener.exe" "%1"'
ASSOCIATIONS = {
    f"Software\\Classes\\{scheme}\\shell\\open\\command": [("", "sz", URL_OPENER)]
    for scheme in ("http", "https")
}
# The Media Foundation transforms the staged decoder DLLs register. Their
# DllRegisterServer calls MFTRegister at run time instead of carrying the keys
# as WINE_REGISTRY resources, so the scripts above do not have them, and a source
# reader finds no decoder (MFTEnumEx reads only these keys). The tables are those
# of the DLLs' DllRegisterServer at the wine pin (dlls/<dll>/<dll>.c), written
# as dlls/mfplat/main.c register_transform and register_category write them;
# the check in generate() drops a row whose DLL is not staged. A type is
# (major, subtype): a str of 4 characters or an int is the FOURCC or format tag
# of a DEFINE_MEDIATYPE_GUID, any other str a GUID.
RGB = "{:08x}-524f-11ce-9f53-0020af0ba770"   # DMOVideoFormat_RGB*: MEDIASUBTYPE_RGB* with data1 = D3DFMT_*
VPROC = ["IYUV", "YV12", "NV12", "YUY2", 0x15, 0x16, "NV11", "AYUV", "UYVY", "P208", 0x14, 0x18, 0x17,
         0x29, "I420", "Y216", "v410", "Y41P", "Y41T", "Y42T", "YVYU"]
CCONV = ["YV12", "YUY2", "UYVY", "AYUV", "NV12", RGB.format(0x16), RGB.format(0x17), "I420", "IYUV", "YVYU",
         RGB.format(0x14), RGB.format(0x18), RGB.format(0x29), "V216", "V410", "NV11"]
MFTS = [  # dll, clsid, category, name, input types, output types (all MFT_ENUM_FLAG_SYNCMFT)
    ("msmpeg2vdec.dll", "62ce7e72-4c71-4d20-b15d-452831a87d9d", "d6c02d4b-6833-45b4-971a-05a4b04bab91",
     "Microsoft H264 Video Decoder MFT",
     [("vids", "H264"), ("vids", "3f40f4f0-5622-4ff8-b6d8-a17a584bee5e")],
     [("vids", s) for s in ("NV12", "YV12", "IYUV", "I420", "YUY2")]),
    ("msauddecmft.dll", "32d186a7-218f-4c75-8876-dd77273a8999", "9ea73fb4-ef7a-4559-8d5d-719d8f0426c7",
     "Microsoft AAC Audio Decoder MFT",
     [("auds", 0x1610), ("auds", 0x00ff), ("auds", 0x1600)], [("auds", 0x3), ("auds", 0x1)]),
    ("msvproc.dll", "88753b26-5b24-49bd-b2e7-0c445c78c982", "302ea3fc-aa5f-47f9-9f7a-c2188bb16302",
     "Microsoft Video Processor MFT",
     [("vids", s) for s in VPROC + ["420O"]], [("vids", s) for s in VPROC]),
    ("colorcnv.dll", "98230571-0087-4204-b020-3282538e57d3", "12e17c21-532c-4a6e-8a1c-40825a736397",
     "Color Converter MFT",
     [("vids", s) for s in CCONV + ["Y41P", "Y41T", "Y42T", "YVU9"]], [("vids", s) for s in CCONV]),
    ("resampledmo.dll", "f447b69e-1884-4a7e-8055-346f74d6edb3", "11064c48-3648-4ed0-932e-05ce8ac811b7",
     "Resampler MFT", [("auds", 0x1), ("auds", 0x3)], [("auds", 0x1), ("auds", 0x3)]),
]
MFT_KEY = "Software\\Classes\\MediaFoundation\\Transforms"


def media_guid(v):
    """A type GUID in memory order (MFT_REGISTER_TYPE_INFO holds GUIDs, not strings)."""
    if isinstance(v, int) or len(v) == 4:
        tag = v if isinstance(v, int) else int.from_bytes(v.encode("latin1"), "little")
        return tag.to_bytes(4, "little") + bytes.fromhex("000010008000" "00aa00389b71")
    return uuid.UUID(v).bytes_le


def register_mfts(hive, staged):
    for dll, clsid, category, name, inputs, outputs in MFTS:
        if dll.lower() not in staged:
            continue
        path = f"{MFT_KEY}\\{clsid}"
        hive.value(path, None, "sz", name)
        hive.value(path, "InputTypes", "binary", b"".join(media_guid(a) + media_guid(b) for a, b in inputs))
        hive.value(path, "OutputTypes", "binary", b"".join(media_guid(a) + media_guid(b) for a, b in outputs))
        hive.value(path, "MFTFlags", "dword", 1)
        hive.key(f"{MFT_KEY}\\Categories\\{category}\\{clsid}")


MARKER = ";; playport:top-up"   # prefix_registry.c recognises it; wineserver skips comments
HEADERS = {"system": ";; All keys relative to REGISTRY\\\\Machine",
           "user": ";; All keys relative to REGISTRY\\\\User\\\\S-1-5-21-0-0-0-1000"}


def scripts(dll):
    """(resource name, script text) for every WINE_REGISTRY resource of a PE."""
    pe = pefile.PE(str(dll), fast_load=True)
    pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_RESOURCE"]])
    for rtype in getattr(pe, "DIRECTORY_ENTRY_RESOURCE", None) and pe.DIRECTORY_ENTRY_RESOURCE.entries or []:
        if str(rtype.name) != "WINE_REGISTRY":
            continue
        for name in rtype.directory.entries:
            for lang in name.directory.entries:
                d = lang.data.struct
                yield str(name.name), pe.get_data(d.OffsetToData, d.Size).decode("utf-8")


def replace(text, module):
    """The registrar's %NAME% replacements; %% is a literal percent."""
    reps = {"MODULE": module, "SYSTEMROOT": SYSTEMROOT}
    out, i = [], 0
    while i < len(text):
        if text[i] != "%":
            out.append(text[i])
            i += 1
            continue
        j = text.index("%", i + 1)
        key = text[i + 1:j]
        out.append("%" if not key else reps[key.upper()])
        i = j + 1
    return "".join(out)


class Script:
    """A registrar script, tokenised as dlls/atl/registrar.c get_word does."""

    def __init__(self, text):
        self.s, self.i = text, 0

    def peek(self):
        return self.s[self.i] if self.i < len(self.s) else ""

    def word(self):
        s = self.s
        while self.i < len(s) and s[self.i].isspace():
            self.i += 1
        if self.i >= len(s):
            return ""
        if s[self.i] in "}=":
            w = s[self.i]
            self.i += 1
        elif s[self.i] == "'":
            parts = []
            while True:
                start = self.i + 1
                end = s.index("'", start)
                if s[end + 1:end + 2] != "'":
                    parts.append(s[start:end])
                    self.i = end + 1
                    break
                parts.append(s[start:end + 1])   # '' is a literal quote
                self.i = end + 1
            w = "".join(parts)
        else:
            start = self.i
            while self.i < len(s) and not s[self.i].isspace():
                self.i += 1
            w = s[start:self.i]
        while self.i < len(s) and s[self.i].isspace():
            self.i += 1
        return w


class Hive:
    def __init__(self):
        self.keys = {}   # lower-case path -> (path, {lower-case value name: (name, type, data)})
        self.deleted = []

    def key(self, path):
        return self.keys.setdefault(path.lower(), (path, {}))[1]

    def value(self, path, name, vtype, data):
        self.key(path)[(name or "").lower()] = (name, vtype, data)


def process_key(sc, hive, parent):
    """do_process_key in register mode: keys are created, values set."""
    w = sc.word()
    while w and w != "}":
        kind = "normal"
        if w.lower() in ("noremove", "forceremove", "val", "delete"):
            kind = w.lower()
            w = sc.word()
        path, name = parent, None
        if kind == "val":
            name = w
        elif kind == "delete":
            hive.deleted.append(f"{parent}\\{w}" if parent else w)
        else:
            path = f"{parent}\\{w}" if parent else w
            hive.key(path)
        if kind != "delete" and sc.peek() == "=":
            sc.i += 1
            vtype = sc.word()
            data = sc.word()
            if vtype == "s":
                hive.value(path, name, "sz", data)
            elif vtype == "d":
                hive.value(path, name, "dword", int(data, 10) & 0xffffffff)
            elif vtype == "b":
                hive.value(path, name, "binary", bytes.fromhex(data))
            else:
                raise SystemExit(f"unknown registrar value type {vtype!r} at {path}")
        elif kind == "val":
            raise SystemExit(f"value {name!r} under {parent} has no data")
        if kind not in ("val", "delete") and sc.peek() == "{" and sc.s[sc.i + 1:sc.i + 2].isspace():
            sc.word()
            process_key(sc, hive, path)
        w = sc.word()


def register(text, hives):
    """do_process_root_key: a sequence of `ROOT { ... }` blocks."""
    sc = Script(text)
    while True:
        root = sc.word()
        if not root:
            return
        if root.upper() not in ROOTS:
            raise SystemExit(f"unknown registrar root {root!r}")
        hive, prefix = ROOTS[root.upper()]
        if sc.word() != "{":
            raise SystemExit(f"expected '{{' after {root}")
        process_key(sc, hives[hive], prefix)


def esc(s):
    """wineserver's dump_strW escaping for key names and string data."""
    out = []
    for ch in s:
        c = ord(ch)
        if ch in '\\"':
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif c < 0x20 or c > 0x7e:
            out.append(f"\\x{c:04x}")
        else:
            out.append(ch)
    return "".join(out)


def render(hive, name, sources, marked):
    lines = ["WINE REGISTRY Version 2", HEADERS[name], "",
             "#arch=win64", "",
             ";; GENERATED by app/tools/prefix-registry.py from the WINE_REGISTRY",
             ";; resources of " + ", ".join(sources) + ",",
             ";; and the user profile keys (PROFILE in that script).",
             ";; wine_host.c appends each section a prefix's hive lacks, before the wineserver starts,",
             ";; and, for a section after a '" + MARKER + "' line, the values a key it has lacks.", ""]
    for low in sorted(hive.keys):
        path, values = hive.keys[low]
        # Keys that only lead to other keys are created on the way; list leaves and keys with values.
        if not values and any(k.startswith(low + "\\") for k in hive.keys):
            continue
        if low in marked:
            lines.append(MARKER)
        lines.append("[" + "\\\\".join(esc(p) for p in path.split("\\")) + "]")
        for vlow in sorted(values):
            vname, vtype, data = values[vlow]
            lhs = "@" if not vname else f'"{esc(vname)}"'
            if vtype == "sz":
                lines.append(f'{lhs}="{esc(data)}"')
            elif vtype == "expand_sz":
                lines.append(f'{lhs}=str(2):"{esc(data)}"')
            elif vtype == "dword":
                lines.append(f"{lhs}=dword:{data:08x}")
            else:
                lines.append(f"{lhs}=hex:" + ",".join(f"{b:02x}" for b in data))
        lines.append("")
    return "\n".join(lines)


def generate():
    hives = {"system": Hive(), "user": Hive()}
    sources = []
    if not RUNTIME.is_dir():
        raise SystemExit(f"{RUNTIME} does not exist; run build/stages/stage-artifacts.py stage first")
    for dll in sorted(RUNTIME.iterdir(), key=lambda p: p.name.lower()):
        if dll.suffix.lower() not in (".dll", ".drv", ".cpl", ".ocx", ".exe"):
            continue
        try:
            found = list(scripts(dll))
        except pefile.PEFormatError:
            continue
        if not found:
            continue
        sources.append(dll.name)
        module = f"{SYSTEM32}\\{dll.name}"
        for _res, text in found:
            register(replace(text, module), hives)
    if not sources:
        raise SystemExit(f"no WINE_REGISTRY resources under {RUNTIME}; run build/stages/stage-artifacts.py stage first")
    register_mfts(hives["system"], {p.name.lower() for p in RUNTIME.iterdir()})
    for name, keys in PROFILE.items():
        for path, values in keys.items():
            for vname, vtype, data in values:
                hives[name].value(path, vname, vtype, data)
    for path, values in ASSOCIATIONS.items():
        for vname, vtype, data in values:
            hives["system"].value(path, vname, vtype, data)
    marked = {name: {path.lower() for path in PROFILE[name]} for name in hives}
    marked["system"] |= {path.lower() for path in ASSOCIATIONS}
    return {f"{name}.reg": render(h, name, sources, marked[name]) for name, h in hives.items()}, hives


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the committed files would change")
    args = ap.parse_args()
    files, hives = generate()
    stale = []
    for name, text in files.items():
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(PKG.parent)))
        else:
            OUT.mkdir(exist_ok=True)
            path.write_text(text)
    nkeys = {n: sum(1 for p, v in h.keys.values()) for n, h in hives.items()}
    clsids = sum(1 for low in hives["system"].keys if low.startswith("software\\classes\\clsid\\{")
                 and low.count("\\") == 3)
    print(f"registry seed: {nkeys['system']} system keys ({clsids} CLSIDs), {nkeys['user']} user keys"
          + (f"; Delete directives ignored: {hives['system'].deleted + hives['user'].deleted}"
             if hives["system"].deleted or hives["user"].deleted else ""))
    if stale:
        sys.exit("stale: " + ", ".join(stale) + " (run pp registry)")
    if args.check:
        print("registry seed verified unchanged")


if __name__ == "__main__":
    main()
